default: &default
  adapter: postgis
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: axs_akl_development

test:
  <<: *default
  database: axs_akl_test

production:
  <<: *default
  database: axs_akl_production
  username: axs_akl
  password: <%= ENV['AXS_AKL_DATABASE_PASSWORD'] %>

